// array med alle produkter
const PRODUCTCOLLECTION = [
    {
        Id: "coffee1",
        Name: "Olhos D’Agua",
        Image: "./img/coffee1.png",
        Origin: "Brazil",
        Price: 99,
        Descritpion: "Typically sweet Brazilian notes of chocolate and toffee are contrasted with a fresh note of black cherry.",
        Notes: {Note1: "Chocolate", Note2: "Cherry", Note3: "Toffeee"},
        Brew: {Brew1: "Espresso", Brew2: "V60", Brew3:"French-press", Brew4: "Aeropress"},
        Roast: "Dark",
    },
    {
        Id: "coffee2",
        Name: "Los Pirineos",
        Image: "./img/coffee2.png",
        Origin: "El Salvador",
        Price: 149,
        Descritpion: "The Carbonic Maceration process creates fresh fruit complexity with soft melon and strawberry notes punctuated by fresh tangerine.",
        Notes: {Note1: "Cantaloupe", Note2: "Tangerine", Note3: "Strawberry"},
        Brew: {Brew1: "Espresso", Brew2: "V60", Brew3:"French-press", Brew4: "Aeropress"},
        Roast: "Light",
    },
    {
        Id: "coffee3",
        Name: "Mukurweini",
        Image: "./img/coffee3.png",
        Origin: "Kenya",
        Price: 139,
        Descritpion: "A rather delicate Kenyan experience, with ripe raspberry joined by notes of black tea and lemon.",
        Notes: {Note1: "Rasberry", Note2: "Lemon", Note3: "Black Tea"},
        Brew: {Brew1: "Espresso", Brew2: "V60", Brew3: "French-press", Brew4: "Aeropress"},
        Roast: "Light",
    },
    {
        Id: "coffee4",
        Name: "Gatukuza #7",
        Image: "./img/coffee4.png",
        Origin: "Burundi",
        Price: 129,
        Descritpion: "A crisp balance between fresh redcurrant acidity and deep honey sweetness is followed by a long finish with notes of rooibos.",
        Notes: {Note1: "Redcurrant", Note2: "Honey", Note3: "Raiboos"},
        Brew: {Brew1: "Espresso", Brew2: "V60", Brew3:"French-press", Brew4: "Aeropress"},
        Roast: "Light",
    },
    {   
        Id: "coffee5",
        Name: "Nzove",
        Image: "./img/coffee4.png",
        Origin: "Burundi",
        Price: 139,
        Descritpion: "Characteristic berry jam notes are joined by wild tropical fruit in this naturally processed lot from the Nzove hill.",
        Notes: {Note1: "Blackberry", Note2: "Mango", Note3: "Brown Sugar"},
        Brew: {Brew1: "Espresso", Brew2: "V60", Brew3:"French-press", Brew4: "Aeropress"},
        Roast: "Light",
    },
    {
        Id: "coffee6",
        Name: "Kiamugumo",
        Image: "./img/coffee4.png",
        Origin: "Kenya",
        Price: 149,
        Descritpion: "Crisp redcurrant is balanced by a caramel sweetness in this fresh and tea-like lot from the Kirinyaga region.",
        Notes: {Note1: "Redcurrant", Note2: "Caramel", Note3: "Black Tea"},
        Brew: {Brew1: "Espresso", Brew2: "V60", Brew3:"French-press", Brew4: "Aeropress"},
        Roast: "Light",
    },
    {
        Id: "coffee7",
        Name: "El Sapo",
        Image: "./img/coffee4.png",
        Origin: "Colombia",
        Price: 165,
        Descritpion: "Crisp redcurrant is balanced by a caramel sweetness in this fresh and tea-like lot from the Kirinyaga region.",
        Notes: {Note1: "Blackberry", Note2: "Sweet Lemon", Note3: "Cherry"},
        Brew: {Brew1: "Espresso", Brew2: "V60", Brew3:"French-press", Brew4: "Aeropress"},
        Roast: "Medium",
    },
    {
        Id: "coffee8",
        Name: "Dingu",
        Image: "./img/coffee4.png",
        Origin: "Ethiopia",
        Price: 152,
        Descritpion: "A natural coffee well produced and dried on African beds on smaller scale from a single producer. A type of coffee more common in Ethiopia since the liberalisation of the industry.",
        Notes: {Note1: "Nougat", Note2: "Raisin", Note3: "Molasses"},
        Brew: {Brew1: "Espresso"},
        Roast: "Dark",
    },
    {
        Id: "coffee9",
        Name: "Colima",
        Image: "./img/coffee4.png",
        Origin: "Costa Rica",
        Price: 176,
        Descritpion: "",
        Notes: {Note1: "Grapes", Note2: "Caramel", Note3: "Stewed Fruits"},
        Brew: {Brew1: "Espresso", Brew2: "V60", Brew3:"French-press", Brew4: "Aeropress"},
        Roast: "Medium",
    },
    {
        Id: "coffee10",
        Name: "Alfredo Baos",
        Image: "./img/coffee4.png",
        Origin: "Colombia",
        Price: 165,
        Descritpion: "",
        Notes: {Note1: "Rasberry", Note2: "Mandarine", Note3: "Brown Sugar"},
        Brew: {Brew2: "V60", Brew3:"French-press", Brew4: "Aeropress"},
        Roast: "Medium",
    },
];


export {PRODUCTCOLLECTION};