// array med alle produkter
const PRODUCTCOLLECTION = [
    {
        Id: "coffee1",
        Name: "Olhos D’Agua",
        Image: "./img/dark.jpg",
        Origin: "Brazil",
        Price: 99,
        Descritpion: "Typically sweet Brazilian notes of chocolate and toffee are contrasted with a fresh note of black cherry.",
        Notes: ["Chocolate", "Cherry", "Toffeee"],
        Brew: ["Espresso", "V60", "French-press", "Aeropress"],
        Roast: "Dark",
    },
    {
        Id: "coffee2",
        Name: "Los Pirineos",
        Image: "./img/light.jpg",
        Origin: "El Salvador",
        Price: 149,
        Descritpion: "The Carbonic Maceration process creates fresh fruit complexity with soft melon and strawberry notes punctuated by fresh tangerine.",
        Notes: ["Cantaloupe", "Tangerine", "Strawberry"],
        Brew: ["Espresso", "V60", "French-press", "Aeropress"],
        Roast: "Light",
    },
    {
        Id: "coffee3",
        Name: "Mukurweini",
        Image: "./img/light.jpg",
        Origin: "Kenya",
        Price: 139,
        Descritpion: "A rather delicate Kenyan experience, with ripe raspberry joined by notes of black tea and lemon.",
        Notes: ["Rasberry", "Lemon", "Black Tea"],
        Brew: ["Espresso", "V60", "French-press", "Aeropress"],
        Roast: "Light",
    },
    {
        Id: "coffee4",
        Name: "Gatukuza #7",
        Image: "./img/light.jpg",
        Origin: "Burundi",
        Price: 129,
        Descritpion: "A crisp balance between fresh redcurrant acidity and deep honey sweetness is followed by a long finish with notes of rooibos.",
        Notes: ["Redcurrant", "Honey", "Raiboos"],
        Brew: ["Espresso", "V60", "French-press", "Aeropress"],
        Roast: "Light",
    },
    {   
        Id: "coffee5",
        Name: "Nzove",
        Image: "./img/dark.jpg",
        Origin: "Burundi",
        Price: 139,
        Descritpion: "Characteristic berry jam notes are joined by wild tropical fruit in this naturally processed lot from the Nzove hill.",
        Notes: ["Blackberry", "Mango", "Brown Sugar"],
        Brew: ["Espresso", "V60", "French-press", "Aeropress"],
        Roast: "Light",
    },
    {
        Id: "coffee6",
        Name: "Kiamugumo",
        Image: "./img/dark.jpg",
        Origin: "Kenya",
        Price: 149,
        Descritpion: "Crisp redcurrant is balanced by a caramel sweetness in this fresh and tea-like lot from the Kirinyaga region.",
        Notes: ["Redcurrant", "Caramel", "Black Tea"],
        Brew: ["Espresso", "V60", "French-press", "Aeropress"],
        Roast: "Light",
    },
];

export {PRODUCTCOLLECTION}